### Objective: Learn Python basics and perform basic data exploration and cleaning using Pandas. Steps: 1.Load a CSV dataset into a Pandas DataFrame. 2.Explore data (head/tail, shape, columns, data types). 3.Handle missing values (identify, fill/drop). 4.Perform basic operations (filter rows, select columns). 5.Remove duplicates. 6.Create a derived column (total_amount = price * quantity). 7.Save the cleaned dataset as a new CSV file. Output: Jupyter Notebook (.ipynb) + cleaned CSV + brief summary.

### 1.Loading a csv file

In [3]:
import pandas as pd
df= pd.read_csv("C:\\praveen\\Datasets\\Combined_dataset.csv")
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

### 2.Explore Data

In [4]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [5]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [6]:
df.shape

(1000, 24)

In [7]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [8]:
df.info

<bound method DataFrame.info of      product_id           title  \
0       8376765     Lino Perros
1       9136281  Tommy Hilfiger
2      17633752           Lavie
3       1376949          F Gear
4      13939916       MYTRIDENT
..          ...             ...
995    13698258           KREDO
996    16896006           GUESS
997     1708108        GIORDANO
998    19280114        Fastrack
999    18601682         BOLDFIT

                                   product_description  rating  ratings_count  \
0                       Women Navy Blue Solid Backpack     3.8             15
1                    Unisex Navy Blue Striped Backpack     4.5             67
2                       Aries Women Pink Mini Backpack     4.4            226
3           Unisex Navy & Grey Printed Burner Backpack     4.4           1052
4                             Men Blue Solid Bath Robe     4.7             12
..                                                 ...     ...            ...
995  Men FORTE Silver Automatic Skeleton Analogue W...     3.5             11
996  Women White Patterned Dial & White Straps Anal...     5.0             22
997  Women Rose Gold-Toned Mirrored Analogue Watch ...     2.8              5
998  Men Black Brass Dial & Black Stainless Steel S...     4.3             17
999                           Purple Textured Yoga Mat     3.8            161

     initial_price  discount   final_price currency  \
0             3995      58.0   "₹3,995.00"      INR
1             2899      35.0   "₹2,899.00"      INR
2             2999      65.0   "₹2,999.00"      INR
3             1675      52.0   "₹1,675.00"      INR
4             2899      17.0   "₹2,899.00"      INR
..             ...       ...           ...      ...
995          11890      50.0  "₹11,890.00"      INR
996           8900      45.0   "₹8,900.00"      INR
997           7950      50.0   "₹7,950.00"      INR
998           3295      20.0   "₹2,636.00"      INR
999            699      31.0     "₹699.00"      INR

                                                images  ...  \
0    http://assets.myntassets.com/assets/images/837...  ...
1    http://assets.myntassets.com/assets/images/913...  ...
2    http://assets.myntassets.com/assets/images/176...  ...
3    http://assets.myntassets.com/assets/images/137...  ...
4    http://assets.myntassets.com/assets/images/pro...  ...
..                                                 ...  ...
995  http://assets.myntassets.com/assets/images/136...  ...
996  http://assets.myntassets.com/assets/images/168...  ...
997  http://assets.myntassets.com/assets/images/170...  ...
998  http://assets.myntassets.com/assets/images/192...  ...
999  http://assets.myntassets.com/assets/images/186...  ...

                                       amount_of_stars what_customers_said  \
0    {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1    {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2    {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3    {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4    {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
..                                                 ...                 ...
995  {"1_star":3,"2_stars":0,"3_stars":2,"4_stars":...                 NaN
996  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
997  {"1_star":2,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
998  {"1_star":1,"2_stars":2,"3_stars":0,"4_stars":...                 NaN
999  {"1_star":24,"2_stars":8,"3_stars":22,"4_stars...                 NaN

        seller_name                                              sizes  \
0               NaN                               [{"size":"Onesize"}]
1               NaN                               [{"size":"Onesize"}]
2               NaN                                     [{"size":"S"}]
3               NaN                               [{"size":"Onesize"}]
4               NaN  [{"size":"M","value":"45.0in","value_name":"Fr...
..              ...                                                ...
995             NaN                               [{"size":"Onesize"}]
996             NaN                               [{"size":"Onesize"}]
997             NaN                               [{"size":"Onesize"}]
998  Tru███m R███il                               [{"size":"Onesize"}]
999             NaN                                [{"size":"Medium"}]

                                                videos  \
0                                ["rw-8376765_cae700"]
1                                ["rw-9136281_cae700"]
2    ["https://videos.myntassets.com/assets/videos/...
3    ["https://videos.myntassets.com/assets/videos/...
4                                                  NaN
..                                                 ...
995                                    ["pi-13698258"]
996  ["rw-16896006_cae700","https://videos.myntasse...
997                                                NaN
998                                                NaN
999                                                NaN

                                    seller_information  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
995                                                NaN
996                                                NaN
997                                                NaN
998  Sho███o. ███-10█████████enu███████████████████...
999                                                NaN

                                      variations  \
0                                           [{}]
1                                        [{},{}]
2                            [{},{},{},{},{},{}]
3                                            NaN
4    [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
..                                           ...
995                                          NaN
996                                          NaN
997                    [{},{},{},{},{},{},{},{}]
998                                          NaN
999                                [{},{},{},{}]

                                            best_offer  \
0                                                   {}
1                                                   {}
2                                                   {}
3                                                   {}
4                                                   {}
..                                                 ...
995                                                 {}
996                                                 {}
997                                                 {}
998  {"applicable_on":"Orders above Rs. 1499 (only ...
999                                                 {}

                                           more_offers   category
0    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4    [{"offer_name":"10% Instant Discount on IndusI...  bath-robe
..                                                 ...        ...
995  [{"offer_name":"10% Instant Discount on Citi C...    watches
996  [{"offer_name":"10% Instant Discount on Citi C...    watches
997  [{"offer_name":"10% Instant Discount on Citi C...    watches
998  [{"offer_name":"10% Instant Discount on IndusI...    watches
999  [{"offer_name":"10% Instant Discount on Citi C...  yoga-mats

[1000 rows x 24 columns]>

In [9]:
df["seller_name"].dtype

dtype('O')

In [10]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

### 3.Handling Missing Values

In [11]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [12]:
df1=df.dropna()
df1

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
418,18689340,Flying Machine,Women Black Wide Leg High-Rise Light Fade Crop...,4.3,36,2349,42.0,"""₹1,362.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":1,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-18689340_cae700""]",10T███LOO███DU █████████ITY███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
752,18241626,Roadster,The Lifestyle Co. Women Maroon & Black Ribbed...,4.5,25,1699,62.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""36.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
753,18241400,Roadster,Women Black & White Geometric Pullover Sweater,3.8,57,2699,5.0,"""₹944.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":5,""2_stars"":4,""3_stars"":13,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""B...","[""rw-18241400_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
754,18241644,Roadster,The Lifestyle Co. Women Pink Acrylic Pullover,4.3,55,1999,62.0,"""₹759.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""38.0in"",""value_name"":""B...","[""rw-18241644_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
755,18240570,all about you,Women Navy Blue & Red Checked Pullover,4.3,53,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18240570_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
756,18240582,all about you,Women Maroon Cable Knit Pullover,4.4,39,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""80"",""value_name"":""Fit, A Littl...",Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
757,18337610,Roadster,Men Navy Blue Self-Striped Cardigan,4.3,32,2299,67.0,"""₹758.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""S"",""value"":""37.0in"",""value_name"":""Ch...","[""rw-18337610_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
760,18241294,Roadster,Women Lavender & Off White Striped Pullover,4.3,90,1699,5.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":8,""2_stars"":0,""3_stars"":7,""4_stars"":...","[{""percentage"":""88"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
762,18241298,Roadster,The Lifestyle Co. Women Lavender Self-Design ...,4.3,59,1999,70.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":8,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""rw-18241298_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
904,18937522,her by invictus,V-Neck Textured Regular Top,3.9,57,1298,65.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":4,""3_stars"":6,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, A Littl...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937522_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [13]:
print(df1.head())

     product_id           title  \
418    18689340  Flying Machine
752    18241626        Roadster
753    18241400        Roadster
754    18241644        Roadster
755    18240570   all about you

                                   product_description  rating  ratings_count  \
418  Women Black Wide Leg High-Rise Light Fade Crop...     4.3             36
752  The  Lifestyle Co. Women Maroon & Black Ribbed...     4.5             25
753     Women Black & White Geometric Pullover Sweater     3.8             57
754     The  Lifestyle Co. Women Pink Acrylic Pullover     4.3             55
755             Women Navy Blue & Red Checked Pullover     4.3             53

     initial_price  discount  final_price currency  \
418           2349      42.0  "₹1,362.00"      INR
752           1699      62.0    "₹645.00"      INR
753           2699       5.0    "₹944.00"      INR
754           1999      62.0    "₹759.00"      INR
755           2499      65.0    "₹874.00"      INR

                                                images  ...  \
418  http://assets.myntassets.com/assets/images/186...  ...
752  http://assets.myntassets.com/assets/images/182...  ...
753  http://assets.myntassets.com/assets/images/182...  ...
754  http://assets.myntassets.com/assets/images/182...  ...
755  http://assets.myntassets.com/assets/images/182...  ...

                                       amount_of_stars  \
418  {"1_star":3,"2_stars":2,"3_stars":1,"4_stars":...
752  {"1_star":0,"2_stars":0,"3_stars":4,"4_stars":...
753  {"1_star":5,"2_stars":4,"3_stars":13,"4_stars"...
754  {"1_star":2,"2_stars":2,"3_stars":3,"4_stars":...
755  {"1_star":2,"2_stars":2,"3_stars":4,"4_stars":...

                                   what_customers_said  \
418  [{"percentage":"50","value_name":"Fit, Just Ri...
752  [{"percentage":"100","value_name":"Fit, Just R...
753  [{"percentage":"67","value_name":"Fit, Just Ri...
754  [{"percentage":"50","value_name":"Fit, Just Ri...
755  [{"percentage":"67","value_name":"Fit, Just Ri...

                           seller_name  \
418  ARV███ LI███TYL█████████LIM██████
752                 Tru███t C███erc███
753                 Tru███t C███erc███
754                 Tru███t C███erc███
755                       Vis███ St███

                                                 sizes  \
418  [{"size":"26","value":"26.0in","value_name":"T...
752  [{"size":"XS","value":"36.0in","value_name":"B...
753  [{"size":"XS","value":"31.0in","value_name":"B...
754  [{"size":"XS","value":"38.0in","value_name":"B...
755  [{"size":"S","value":"34.0in","value_name":"To...

                                                videos  \
418                             ["rw-18689340_cae700"]
752  ["https://videos.myntassets.com/assets/videos/...
753  ["rw-18241400_cae700","https://videos.myntasse...
754  ["rw-18241644_cae700","https://videos.myntasse...
755                             ["rw-18240570_cae700"]

                                    seller_information variations  \
418  10T███LOO███DU █████████ITY███████████████████...    [{},{}]
752  1 s███loo███Cab█████████-01███████████████████...    [{},{}]
753  1 s███loo███Cab█████████-01███████████████████...    [{},{}]
754  1 s███loo███Cab█████████-01███████████████████...    [{},{}]
755  3rd███oor███o. █████████Mai███████████████████...       [{}]

                                            best_offer  \
418  {"applicable_on":"Orders above Rs. 1499 (only ...
752  {"applicable_on":"Orders above Rs. 749 (only o...
753  {"applicable_on":"Orders above Rs. 1099 (only ...
754  {"applicable_on":"Orders above Rs. 749 (only o...
755  {"applicable_on":"Orders above Rs. 999 (only o...

                                           more_offers  category
418  [{"offer_name":"10% Instant Discount on IndusI...     jeans
752  [{"offer_name":"10% Instant Discount on IndusI...  sweaters
753  [{"offer_name":"10% Instant Discount on IndusI...  sweaters
754  [{"offer_name":"10% Instant Discount on IndusI...  sweaters
755  [{"offer_name":"10% Instant Discount on IndusI...  sweaters

[5 rows x 24 columns]

In [14]:
df1.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

### 4.basic operations (filter rows, select columns)

In [15]:
df[df["rating"]>4.2]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,NaN,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",NaN,DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

In [16]:
df[["product_id","title","rating","final_price","seller_name","category"]]

,product_id,title,rating,final_price,seller_name,category
0,8376765,Lino Perros,3.8,"""₹3,995.00""",NaN,backpacks
1,9136281,Tommy Hilfiger,4.5,"""₹2,899.00""",NaN,backpacks
2,17633752,Lavie,4.4,"""₹2,999.00""",NaN,backpacks
3,1376949,F Gear,4.4,"""₹1,675.00""",NaN,backpacks
4,13939916,MYTRIDENT,4.7,"""₹2,899.00""",NaN,bath-robe
...,...,...,...,...,...,...
995,13698258,KREDO,3.5,"""₹11,890.00""",NaN,watches
996,16896006,GUESS,5.0,"""₹8,900.00""",NaN,watches
997,1708108,GIORDANO,2.8,"""₹7,950.00""",NaN,watches
998,19280114,Fastrack,4.3,"""₹2,636.00""",Tru███m R███il,watches
999,18601682,BOLDFIT,3.8,"""₹699.00""",NaN,yoga-mats

### 5.Remove Duplicates

In [17]:
df1=df1.drop_duplicates()

In [18]:
df1

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
418,18689340,Flying Machine,Women Black Wide Leg High-Rise Light Fade Crop...,4.3,36,2349,42.0,"""₹1,362.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":1,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-18689340_cae700""]",10T███LOO███DU █████████ITY███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
752,18241626,Roadster,The Lifestyle Co. Women Maroon & Black Ribbed...,4.5,25,1699,62.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""36.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
753,18241400,Roadster,Women Black & White Geometric Pullover Sweater,3.8,57,2699,5.0,"""₹944.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":5,""2_stars"":4,""3_stars"":13,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""B...","[""rw-18241400_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
754,18241644,Roadster,The Lifestyle Co. Women Pink Acrylic Pullover,4.3,55,1999,62.0,"""₹759.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""38.0in"",""value_name"":""B...","[""rw-18241644_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
755,18240570,all about you,Women Navy Blue & Red Checked Pullover,4.3,53,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18240570_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
756,18240582,all about you,Women Maroon Cable Knit Pullover,4.4,39,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""80"",""value_name"":""Fit, A Littl...",Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
757,18337610,Roadster,Men Navy Blue Self-Striped Cardigan,4.3,32,2299,67.0,"""₹758.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""S"",""value"":""37.0in"",""value_name"":""Ch...","[""rw-18337610_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
760,18241294,Roadster,Women Lavender & Off White Striped Pullover,4.3,90,1699,5.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":8,""2_stars"":0,""3_stars"":7,""4_stars"":...","[{""percentage"":""88"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
762,18241298,Roadster,The Lifestyle Co. Women Lavender Self-Design ...,4.3,59,1999,70.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":8,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""rw-18241298_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
904,18937522,her by invictus,V-Neck Textured Regular Top,3.9,57,1298,65.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":4,""3_stars"":6,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, A Littl...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937522_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [19]:
df1.duplicated().sum()

np.int64(0)

### 6.derived column (total_amount = price * quantity),(quantity column not given in dataset)

In [20]:
df1["quantity"]=1 
df1["total_amount"]=df1["final_price"]*df1["quantity"]

In [21]:
df1

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
418,18689340,Flying Machine,Women Black Wide Leg High-Rise Light Fade Crop...,4.3,36,2349,42.0,"""₹1,362.00""",INR,http://assets.myntassets.com/assets/images/186...,...,ARV███ LI███TYL█████████LIM██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-18689340_cae700""]",10T███LOO███DU █████████ITY███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,1,"""₹1,362.00"""
752,18241626,Roadster,The Lifestyle Co. Women Maroon & Black Ribbed...,4.5,25,1699,62.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Tru███t C███erc███,"[{""size"":""XS"",""value"":""36.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹645.00"""
753,18241400,Roadster,Women Black & White Geometric Pullover Sweater,3.8,57,2699,5.0,"""₹944.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Tru███t C███erc███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""B...","[""rw-18241400_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹944.00"""
754,18241644,Roadster,The Lifestyle Co. Women Pink Acrylic Pullover,4.3,55,1999,62.0,"""₹759.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Tru███t C███erc███,"[{""size"":""XS"",""value"":""38.0in"",""value_name"":""B...","[""rw-18241644_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹759.00"""
755,18240570,all about you,Women Navy Blue & Red Checked Pullover,4.3,53,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18240570_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹874.00"""
756,18240582,all about you,Women Maroon Cable Knit Pullover,4.4,39,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹874.00"""
757,18337610,Roadster,Men Navy Blue Self-Striped Cardigan,4.3,32,2299,67.0,"""₹758.00""",INR,http://assets.myntassets.com/assets/images/183...,...,Tru███t C███erc███,"[{""size"":""S"",""value"":""37.0in"",""value_name"":""Ch...","[""rw-18337610_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹758.00"""
760,18241294,Roadster,Women Lavender & Off White Striped Pullover,4.3,90,1699,5.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Tru███t C███erc███,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹628.00"""
762,18241298,Roadster,The Lifestyle Co. Women Lavender Self-Design ...,4.3,59,1999,70.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Tru███t C███erc███,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""rw-18241298_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹699.00"""
904,18937522,her by invictus,V-Neck Textured Regular Top,3.9,57,1298,65.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937522_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,1,"""₹454.00"""

### 7.saving the clean dataset

In [22]:
df1.to_csv("cleaned_shopping.csv",index=False)